#!/bin/sh

GUNICORN=$SV_GUNICORN
ROOT=$SV_ROOT
#PID=/var/run/gunicorn.pid

APP=studentools.wsgi:application

#if [ -f $PID ]; then rm $PID; fi

cd $ROOT
exec $GUNICORN -w 3 -c $ROOT/gunicorn.conf.py --pid=$PID $APP
